name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: node-${{ matrix.node }}
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
