name: Integration tests

on: [deployment_status]

jobs:
  build:
    if: github.event.deployment_status.state == 'success'
    name: query-for-torrents
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Make GraphQL request
        id: gqlRequest
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ github.event.deployment_status.target_url }}
          method: "POST"
          data: |
            {
              "query": "query GetTorrents { torrents(query: \"sintel 2010\", providers: [PROVIDER_LIMETORRENTS]) { title size peers seeds }}"
            }
      - name: Show Response
        run: echo ${{ steps.gqlRequest.outputs.response }}

      - name: Integration tests passed
        if: ${{ success() }}

        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "integration-tests",
            "state": "success",
            "description": "Integration tests passed",
            "target_url": "'"$GITHUB_SERVER_URL"'/'"$GITHUB_REPOSITORY"'/actions/runs/'"$GITHUB_RUN_ID"'"
          }'
      - name: Integration tests failed
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "integration-tests",
            "state": "failure",
            "description": "Integration tests failed",
            "target_url": "'"$GITHUB_SERVER_URL"'/'"$GITHUB_REPOSITORY"'/actions/runs/'"$GITHUB_RUN_ID"'"
          }'
